FROM hypi/fenrir-runtime-python:v1

COPY src/main.py /home/hypi/fenrir/function/main.py
#If you have dependencies specified in requirements.txt then add a line like this
#RUN cd /home/hypi/fenrir/function; pip install -r requirements.txt
#OR just run pip install
#RUN pip install my-dependency
